# Generated by Django 2.1.5 on 2019-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_time', models.DateTimeField(auto_now_add=True, verbose_name='保存日期')),
            ],
        ),
    ]
